// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetConfig():Promise<config.Config>;

export function GetServerStatus():Promise<Record<string, any>>;

export function GetVersion():Promise<string>;

export function RespondToSignRequest(arg1:string,arg2:boolean):Promise<void>;

export function SetConfig(arg1:config.Config):Promise<void>;

export function SetEnabled(arg1:boolean):Promise<config.Config>;

export function ValidateKey():Promise<Record<string, any>>;

export function ValidateKeyPath(arg1:string):Promise<Record<string, any>>;
