// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}

export function SetEnabled(arg1) {
  return window['go']['main']['App']['SetEnabled'](arg1);
}

export function ValidateKey() {
  return window['go']['main']['App']['ValidateKey']();
}

export function ValidateKeyPath(arg1) {
  return window['go']['main']['App']['ValidateKeyPath'](arg1);
}
